allhpc <- read.table('household_power_consumption.txt',header=TRUE,sep=';',na.strings='?')
library('dplyr')
allhpc$Date<-as.Date(allhpc$Date, format='%d/%m/%Y')
hpcdata <- filter(allhpc, Date=='2007-02-01' | Date=='2007-02-02')
hpcdata<-mutate(hpcdata,timestamp=format(as.POSIXct(paste(Date,Time)),"%d/%m/%Y %H:%M:%S"))
hpcdata$timestamp<-strptime(hpcdata$timestamp,format="%d/%m/%Y %H:%M:%S")
png(file='plot1.png')
hist(hpcdata$Global_active_power, col='red', main='Global Active Power',xlab='Global Active Power (kilowatts)')
dev.off()