allhpc <- read.table('household_power_consumption.txt',header=TRUE,sep=';',na.strings='?')
library('dplyr')
allhpc$Date<-as.Date(allhpc$Date, format='%d/%m/%Y')
hpcdata <- filter(allhpc, Date=='2007-02-01' | Date=='2007-02-02')
hpcdata<-mutate(hpcdata,timestamp=format(as.POSIXct(paste(Date,Time)),"%d/%m/%Y %H:%M:%S"))
hpcdata$timestamp<-strptime(hpcdata$timestamp,format="%d/%m/%Y %H:%M:%S")
png(file='plot3.png')
plot(hpcdata$timestamp,hpcdata$Sub_metering_1,type='n',xlab='',ylab='Energy sub metering')
lines(hpcdata$timestamp, hpcdata$Sub_metering_1, type='l', col='black')
lines(hpcdata$timestamp, hpcdata$Sub_metering_2, type='l', col='red')
lines(hpcdata$timestamp, hpcdata$Sub_metering_3, type='l', col='blue')
legend("topright",col=c('black','red','blue'),lwd=1,lty=c(1,1,1),legend=names(hpcdata)[7:9])
dev.off()