allhpc <- read.table('household_power_consumption.txt',header=TRUE,sep=';',na.strings='?')
library('dplyr')
allhpc$Date<-as.Date(allhpc$Date, format='%d/%m/%Y')
hpcdata <- filter(allhpc, Date=='2007-02-01' | Date=='2007-02-02')
hpcdata<-mutate(hpcdata,timestamp=format(as.POSIXct(paste(Date,Time)),"%d/%m/%Y %H:%M:%S"))
hpcdata$timestamp<-strptime(hpcdata$timestamp,format="%d/%m/%Y %H:%M:%S")
png(file='plot2.png')
plot(hpcdata$timestamp,hpcdata$Global_active_power,type='n',xlab='',ylab='Global Active Power (kilowatts)')
lines(hpcdata$timestamp, hpcdata$Global_active_power, type='l')
dev.off()